# @aegisFrameworkVersion: 2.1.0
# @intent: Constitutional enforcement configuration
# @context: Framework governance and protection system configuration

framework:
  version: "2.1.0"
  enforcement:
    destructiveActionProtection:
      enabled: true
      riskLevels:
        - low
        - medium
        - high
        - critical
      essentialFiles:
        - "CONSTITUTION.md"
        - "VERSION"
        - "package.json"
        - "tsconfig.json"
        - "README.md"
        - "CHANGELOG.md"
        - "CONTRIBUTING.md"
        - "LICENSE"
      essentialDirectories:
        - "framework/"
        - "docs/"
        - "cli/"
        - "tools/"
        - "blueprints/"
        - "adapters/"
        - "tests/"
        - "examples/"
        - "templates/"
        - "scaffolds/"
    
    preCommitHooks:
      enabled: true
      destructivePatterns:
        - "rm -rf"
        - "rm -r"
        - "rm -f"
        - "rm -rf ."
        - "rm -rf /"
        - "rm -rf node_modules"
        - "rm -rf dist"
        - "rm -rf .framework"
        - "rm -rf .aegis"
        - "rm -rf .vscode"
        - "rm -rf .cursor"
    
    constitutionalCompliance:
      requiredAnnotations:
        - "@aegisFrameworkVersion"
        - "@intent"
        - "@context"
        - "@mode"
      versionConsistency:
        enabled: true
        files:
          - "VERSION"
          - "README.md"
          - "CHANGELOG.md"
          - "framework/framework-core-v2.1.0.md"
          - ".github/copilot-instructions.md"
    
    emergencyRecovery:
      enabled: true
      autoRestore:
        enabled: true
        maxBackupAge: "7d"
      frameworkState:
        backupInterval: "1h"
        retentionPeriod: "30d"

cursor:
  integration:
    enabled: true
    realTimeDetection:
      enabled: true
      sessionAnalysis: true
      visualFeedback: true
    evolutionStoryGeneration:
      enabled: true
      autoCapture: true

build:
  system:
    vite:
      enabled: true
      optimization: true
    bun:
      enabled: true
      runtime: true
    typescript:
      moduleResolution: "bundler"
      noEmit: true
      strict: false
