# Aegis Framework Team Configuration - Minimal Profile
# Generated: 2025-08-06T00:00:00Z
# Framework Version: 2.4.0-alpha-dev
# WARNING: This configuration disables required features

team:
  name: "Minimal Configuration Team"
  profile: "minimal"
  constitutionalAcknowledgment: "2025-08-06"

# CORE features (cannot be disabled)
core:
  blueprintValidation: true
  agentDriftPrevention: true
  intentEnforcement: true
  versionConsistency: true

# REQUIRED features (disabled with constitutional override)
required:
  evolutionStoryDetection:
    enabled: false # OVERRIDE: Requires acknowledgment
    autoGenerate: false
    triggerThreshold: "high" # Higher threshold when enabled

  constitutionalEnforcement:
    mode: "advisory" # OVERRIDE: Warning-only mode
    blocking: false # OVERRIDE: Non-blocking
    autoCorrection: false

  precommitHooks:
    enabled: false # OVERRIDE: No pre-commit enforcement
    evolutionDetection: false
    constitutionalValidation: false

  annotations:
    required: false # OVERRIDE: Optional annotations
    coverage: 0.5 # Lower coverage requirement
    enforcement: "silent" # No enforcement

  templateQuality:
    validation: false # OVERRIDE: No template validation
    encodingChecks: false

# OPTIONAL features (all disabled for minimal profile)
optional:
  realtimePatternDetection:
    enabled: false
    sensitivity: "low"

  autoGeneratedEvolutionStories:
    enabled: false
    severity: "critical"

  driftMonitoringDashboard:
    enabled: false
    updateInterval: "weekly"

  automatedChangelog:
    enabled: false
    format: "standard"

  predictiveEnforcement:
    enabled: false
    confidence: 0.9
    learning: false

# Constitutional overrides (REQUIRED for minimal profile)
overrides:
  constitutionalAcknowledgment: "2025-08-06"
  reason: "Team requires maximum development flexibility during early prototyping phase"
  approvedBy: "tech-lead@minimal-team.com"
  overrideExpiry: "2025-12-06" # 4 months maximum
