# Aegis Framework Team Configuration Example
# Generated: 2025-08-06T00:00:00Z
# Framework Version: 2.0.0-alpha-dev

team:
  name: "Example Development Team"
  profile: "balanced"
  constitutionalAcknowledgment: "2025-08-06"

# CORE features (cannot be disabled)
core:
  blueprintValidation: true
  agentDriftPrevention: true
  intentEnforcement: true
  versionConsistency: true

# REQUIRED features (on by default, team can override)
required:
  evolutionStoryDetection:
    enabled: true
    autoGenerate: false
    triggerThreshold: "medium"
    
  constitutionalEnforcement:
    mode: "guided"
    blocking: true
    autoCorrection: true
    
  precommitHooks:
    enabled: true
    evolutionDetection: true
    constitutionalValidation: true
    
  annotations:
    required: true
    coverage: 0.8
    enforcement: "warning"
    
  templateQuality:
    validation: true
    encodingChecks: true

# OPTIONAL features (off by default)
optional:
  realtimePatternDetection:
    enabled: false
    sensitivity: "medium"
    
  autoGeneratedEvolutionStories:
    enabled: false
    severity: "critical"
    
  driftMonitoringDashboard:
    enabled: false
    updateInterval: "daily"
    
  automatedChangelog:
    enabled: false
    format: "constitutional"
    
  predictiveEnforcement:
    enabled: false
    confidence: 0.8
    learning: true

# No overrides needed for balanced profile
# overrides:
#   constitutionalAcknowledgment: "2025-08-06"
#   reason: "Team workflow optimization"
#   approvedBy: "tech-lead@team.com"
#   overrideExpiry: "2025-12-06"
