import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Capabilities sidebar (auto-generated from framework data)
  capabilitiesSidebar: [
    {
      type: 'doc',
      id: 'capabilities/overview',
      label: 'Capabilities Overview',
    },
    {
      type: 'category',
      label: 'Categories',
      items: ['capabilities/tools', 'capabilities/core', 'capabilities/governance', 'capabilities/integration'],
    },
  ],

  // Blueprints sidebar
  blueprintsSidebar: [
    {
      type: 'doc',
      id: 'blueprints/overview',
      label: 'Blueprint Registry',
    },
    {
      type: 'category',
      label: 'Available Blueprints',
      items: ['blueprints/feat-public-viewing'],
    },
  ],
};

export default sidebars;
