name: Aegis Compliance

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run Aegis Compliance
        run: pnpm aegis:compliance:json
      - name: Run Compliance Tests
        run: pnpm test:compliance
