name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
      - 'docs/**'
      - 'README.md'
      - 'CONSTITUTION.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '18'
          
      - name: Install dependencies
        run: cd website && bun install
        
      - name: Build and Deploy to GitHub Pages
        run: |
          cd website
          npm run build
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
